# Generated by Django 2.2.6 on 2021-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialead',
            name='results',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
