# Generated by Django 2.2.6 on 2021-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
