# Generated by Django 2.2.6 on 2019-10-10 17:53

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
