# Generated by Django 2.2.6 on 2021-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
