# Generated by Django 2.2.6 on 2019-10-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_10',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_7',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_8',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_9',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_1',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_10',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_2',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_3',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_4',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_5',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_6',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_7',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_8',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson_9',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
