# Generated by Django 2.2.6 on 2019-10-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Document',
        ),
    ]
