# Generated by Django 2.2.6 on 2019-10-23 19:01

import courses.models
import courses.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20191023_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=courses.models.course_upload_location),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=courses.models.file_upload_location, validators=[courses.validators.validate_file_size]),
        ),
    ]
